name: Apply Tutor Updates

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello Master Taru, Actions is alive!"

      - name: List files in repo
        run: ls -R
