name: Apply Tutor Updates

on:
  workflow_dispatch:   # lets you run it manually from GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello Master Taru, Actions is alive!"
